### ISSUE TITLE
influxdb-queries not starting

### ISSUE THREAD

**Issue by stephenrenshaw** [ajgb/go-opsview#1]
I've followed the instructions and configured data_dir to match my opsview rrd timeseries data path,  when i start bin/influxdb-queries it exits, i assume this is because the opsview-timeseries service is already listening on port 1660, can i change the port or do i need to disable the opsview-timeseriesrrdqueries service?

---
timeseriesinfluxdb:
    server:
        user: opsview
        password: opsview
        updates:
            host: 127.0.0.1
            workers:
                - port: 1640
                - port: 1641
                - port: 1642
                - port: 1643
            logging:
                loggers:
                    opsview:
                        level: NOTICE
        queries:
            host: 127.0.0.1
            port: 1660
            logging:
                loggers:
                    opsview:
                        level: NOTICE
    data_dir: /opt/opsview/timeseriesrrd/var/data
    influxdb:
        server: http://192.168.60.57:8086
        user:
        password:
        database: opsview
        retention_policy: default

**Comment by ajgb** [comment]
You can either remove `opsview-timeseries-rrd` so that the both `influxdb-queries` and `influxdb-updaters` just jump in the ports used by the `opsview-timeseries` and `opsview-timeseries-enqueuer` or reconfigure those two packages and the influxdb provider to use different ports.

I'd suggest removing the `opsview-timeseries-rrd` - the `value.rrd` files will not be removed on uninstall.
